name: Python application

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python 3.14
        uses: actions/setup-python@v5
        with:
          python-version: "3.14.3"

      - name: Install dependencies
        run: pip install -r src/requirements.txt

      - name: Lint code with Ruff
        run: ruff check src

      - name: Test with pytest
        working-directory: src
        run: python test.py
